version: '3.8'
services:
 db-mysql:
  container_name: db-mysql
  image: mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    MYSQL_DATABASE: u576316930_nupj
    MYSQL_USER: MYSQL_USER
    MYSQL_PASSWORD: MYSQL_PASSWORD
  ports:
  - "9606:3306"
  expose:
      # Opens port 3306 on the container
    - '3306'
      # Where our data will be persisted
  volumes:
    - . / mysql-data:/var/lib/mysql

 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - "8800:80"
   restart: always
   environment:
    PMA_HOST: db-mysql
   depends_on:
    - db-mysql
    
 db-postgres:
    container_name: db-postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./ db-postgres:/var/lib/postgresql/data
volumes:
  db:
    driver: local

    