version: '3.8'
services:
  php-apache-environment:
    container_name: PHP-Webapp-only
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./php/scr:/var/www/html/
    ports:
      - 8890:80
  portainer:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    image: portainer/portainer
    volumes:
      - portainer_data:/data
      - ./php/scr:/var/run/docker.sock

    ports:
      - "8899:9000"
volumes: 
  portainer_data:

networks:
    default:
      external: true
      name: webproxy