version: '3.8'
services:
  php-apache-environment:
    container_name: PHP-Webapp-only
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./php/scr:/var/www/html/
    ports:
      - 8890:80
  portainer:
    image: portainer/portainer-ce:latest
    volumes:
        - data:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
      - "8899:9000"
volumes: 
  portainer_data:

networks:
    default:
      external: true
      name: webproxy