version: '3.8'
services:
  php-apache-environment:
    container_name: PHP-Webapp
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/scr:/var/www/html/
    ports:
      - 8890:80

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      -"80:80"
  volumes:
    - . /var/run/docker.sock:/tmp/docker.sock:ro