version: '3.8'
services:
  php-apache-environment:
    container_name: PHP-Webapp
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/scr:/var/www/html/
    ports:
      - 8890:80