version: '3.8'
services:
  php-apache-environment:
    container_name: PHP-Webapp-only
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./php/scr:/var/www/html/
    ports:
      - 8890:80


networks:
    default:
      external: true
      name: public